services:
  _defaults:
    autowire: true

  Webgriffe\Esb\Service\:
    resource: 'src/Service/*'

  Webgriffe\Esb\FlowManager:
    public: true

  Amp\Beanstalk\BeanstalkClient:
    arguments: [ '%beanstalkd%' ]
    shared: false

  Webgriffe\Esb\Service\HttpProducersServer:
    arguments:
      $port: '%http_server_port%'

  Monolog\Handler\StreamHandler:
    class: \Monolog\Handler\StreamHandler
    arguments: [ 'php://stdout', !php/const:Monolog\Logger::DEBUG ]

  Monolog\Handler\ErrorLogHandler:
    class: \Monolog\Handler\ErrorLogHandler
    arguments: [ !php/const:Monolog\Handler\ErrorLogHandler::OPERATING_SYSTEM, !php/const:Monolog\Logger::ERROR ]

  Monolog\Formatter\HtmlFormatter: {}

  Monolog\Handler\NativeMailerHandler:
    class: \Monolog\Handler\NativeMailerHandler
    arguments: [ '%logger_mail_to%', 'Significant event from ESB', '%logger_mail_from%', !php/const:Monolog\Logger::WARNING ]
    calls:
      - method: setFormatter
        arguments:
          - '@Monolog\Formatter\HtmlFormatter'
      - method: setContentType
        arguments:
          - 'text/html'


  Psr\Log\LoggerInterface:
    class: \Monolog\Logger
    arguments: [ 'esb', ['@Monolog\Handler\StreamHandler', '@Monolog\Handler\ErrorLogHandler', '@Monolog\Handler\NativeMailerHandler'] ]
    public: true

  Webgriffe\Esb\DateTimeBuilderInterface:
    class: \Webgriffe\Esb\DateTimeBuilder

  console_logger.stream_handler:
    class: \Monolog\Handler\StreamHandler
    arguments: [ '%console_log_file%' ]

  console_logger:
    class: \Monolog\Logger
    arguments: ['esb_console', ['@console_logger.stream_handler']]

  Webgriffe\Esb\Console\Server:
    class: \Webgriffe\Esb\Console\Server
    arguments:
      - '@Amp\Beanstalk\BeanstalkClient'
      -
        port: '%console_port%'
        username: '%console_username%'
        password: '%console_password%'
      - '@console_logger'
    public: true
